#!/usr/bin/env python3
"""
generate_charts.py — Chart generator for the INFO 579 portfolio project.

Produces 4 PNG bar charts from the populated MySQL database:
  images/top_conditions.png          - Top 10 conditions by patient count
  images/top_procedures.png          - Top 10 procedures by volume
  images/top_providers.png           - Top 10 providers by encounter count
  images/coverage_distribution.png   - Patient coverage tier breakdown

(The ER diagram at images/schema_er_diagram.png is a hand-curated screenshot
and is NOT regenerated by this script.)

Prerequisites
-------------
- matplotlib, pandas, mysql-connector-python
- MySQL 8+ running with data already loaded via load_csvs.py

Usage
-----
    python scripts/generate_charts.py --user matthewqthompson --database Final_Project

    # Password from environment variable:
    export MYSQL_PASSWORD="TempPass2026!"
    python scripts/generate_charts.py --user matthewqthompson --database Final_Project
"""

import argparse
import getpass
import os
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Project root — works regardless of cwd
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
IMAGES_DIR = PROJECT_ROOT / "images"


# ---------------------------------------------------------------------------
# Chart helpers
# ---------------------------------------------------------------------------

def _apply_chart_style() -> None:
    """Apply the shared matplotlib style used across all charts."""
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]

    try:
        plt.style.use("seaborn-v0_8-whitegrid")
    except OSError:
        # Older matplotlib versions name the style without the version suffix
        try:
            plt.style.use("seaborn-whitegrid")
        except OSError:
            pass  # Fall back to default if neither is available


def _save_fig(fig, output_path: Path) -> None:
    """Save figure to PNG at 150 DPI with tight layout."""
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"  Saved: {output_path}")


def _fmt_count(n: int) -> str:
    """Format an integer with thousands separator."""
    return f"{n:,}"


# ---------------------------------------------------------------------------
# Chart generators
# ---------------------------------------------------------------------------

def generate_top_conditions(conn, output_path: Path) -> None:
    """Horizontal bar chart — top 10 conditions by distinct patient count."""
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]
    import matplotlib.ticker as mticker  # type: ignore[import-not-found]

    query = textwrap.dedent("""
        SELECT condition_description, COUNT(DISTINCT patient_id) AS n_patients
        FROM medical_condition
        GROUP BY condition_description
        ORDER BY n_patients DESC
        LIMIT 10
    """).strip()

    cursor = conn.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    cursor.close()

    if not rows:
        print("  WARNING: No data returned for top_conditions. Skipping chart.")
        return

    labels = [r[0] for r in rows]
    values = [r[1] for r in rows]

    # Reverse so the largest bar is at the top
    labels = labels[::-1]
    values = values[::-1]

    _apply_chart_style()
    fig, ax = plt.subplots(figsize=(12, 7))

    bars = ax.barh(
        labels, values,
        color="#4682B4",
        edgecolor="white",
        linewidth=0.5,
        height=0.65,
    )

    # Annotate bars with count
    for bar, v in zip(bars, values):
        ax.text(
            bar.get_width() + max(values) * 0.005,
            bar.get_y() + bar.get_height() / 2,
            _fmt_count(v),
            va="center",
            ha="left",
            fontsize=9,
            color="#333333",
        )

    ax.set_xlabel("Number of Patients", fontsize=11, labelpad=8)
    ax.set_title("Top 10 Conditions by Patient Count", fontsize=14, fontweight="bold", pad=14)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.set_xlim(0, max(values) * 1.12)
    ax.tick_params(axis="y", labelsize=9)
    ax.tick_params(axis="x", labelsize=9)

    # Trim long labels so the chart stays readable
    wrapped = [textwrap.fill(lbl, width=45) for lbl in labels]
    ax.set_yticklabels(wrapped)

    fig.tight_layout()
    _save_fig(fig, output_path)
    plt.close(fig)


def generate_top_procedures(conn, output_path: Path) -> None:
    """Horizontal bar chart — top 10 procedures by total volume."""
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]
    import matplotlib.ticker as mticker  # type: ignore[import-not-found]

    query = textwrap.dedent("""
        SELECT procedure_description, COUNT(*) AS n_procedures
        FROM procedures
        GROUP BY procedure_description
        ORDER BY n_procedures DESC
        LIMIT 10
    """).strip()

    cursor = conn.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    cursor.close()

    if not rows:
        print("  WARNING: No data returned for top_procedures. Skipping chart.")
        return

    labels = [r[0] for r in rows]
    values = [r[1] for r in rows]

    labels = labels[::-1]
    values = values[::-1]

    _apply_chart_style()
    fig, ax = plt.subplots(figsize=(12, 7))

    bars = ax.barh(
        labels, values,
        color="#2E8B57",
        edgecolor="white",
        linewidth=0.5,
        height=0.65,
    )

    for bar, v in zip(bars, values):
        ax.text(
            bar.get_width() + max(values) * 0.005,
            bar.get_y() + bar.get_height() / 2,
            _fmt_count(v),
            va="center",
            ha="left",
            fontsize=9,
            color="#333333",
        )

    ax.set_xlabel("Number of Procedures", fontsize=11, labelpad=8)
    ax.set_title("Top 10 Procedures by Volume", fontsize=14, fontweight="bold", pad=14)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.set_xlim(0, max(values) * 1.12)
    ax.tick_params(axis="y", labelsize=9)
    ax.tick_params(axis="x", labelsize=9)

    wrapped = [textwrap.fill(lbl, width=45) for lbl in labels]
    ax.set_yticklabels(wrapped)

    fig.tight_layout()
    _save_fig(fig, output_path)
    plt.close(fig)


def generate_top_providers(conn, output_path: Path) -> None:
    """Horizontal bar chart — top 10 providers by encounter count from rpt_provider_utilization."""
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]
    import matplotlib.ticker as mticker  # type: ignore[import-not-found]

    query = textwrap.dedent("""
        SELECT CONCAT(provider_name, ' (', provider_specialty, ')') AS provider_label,
               n_encounters
        FROM rpt_provider_utilization
        ORDER BY n_encounters DESC
        LIMIT 10
    """).strip()

    cursor = conn.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    cursor.close()

    if not rows:
        print("  WARNING: No data returned for top_providers. Skipping chart.")
        return

    labels = [r[0] for r in rows]
    values = [r[1] for r in rows]

    labels = labels[::-1]
    values = values[::-1]

    _apply_chart_style()
    fig, ax = plt.subplots(figsize=(13, 7))

    bars = ax.barh(
        labels, values,
        color="#6A5ACD",
        edgecolor="white",
        linewidth=0.5,
        height=0.65,
    )

    for bar, v in zip(bars, values):
        ax.text(
            bar.get_width() + max(values) * 0.005,
            bar.get_y() + bar.get_height() / 2,
            _fmt_count(v),
            va="center",
            ha="left",
            fontsize=9,
            color="#333333",
        )

    ax.set_xlabel("Number of Encounters", fontsize=11, labelpad=8)
    ax.set_title("Top 10 Providers by Encounter Volume", fontsize=14, fontweight="bold", pad=14)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.set_xlim(0, max(values) * 1.12)
    ax.tick_params(axis="y", labelsize=9)
    ax.tick_params(axis="x", labelsize=9)

    wrapped = [textwrap.fill(lbl, width=50) for lbl in labels]
    ax.set_yticklabels(wrapped)

    fig.tight_layout()
    _save_fig(fig, output_path)
    plt.close(fig)


def generate_coverage_distribution(conn, output_path: Path) -> None:
    """Vertical bar chart — patient count by healthcare coverage tier (high/medium/low)."""
    import matplotlib.pyplot as plt  # type: ignore[import-not-found]
    import matplotlib.ticker as mticker  # type: ignore[import-not-found]

    query = textwrap.dedent("""
        SELECT
          SUM(CASE WHEN healthcare_coverage >= 10000 THEN 1 ELSE 0 END)                                    AS high_coverage,
          SUM(CASE WHEN healthcare_coverage >= 5000 AND healthcare_coverage < 10000 THEN 1 ELSE 0 END)     AS medium_coverage,
          SUM(CASE WHEN healthcare_coverage < 5000 THEN 1 ELSE 0 END)                                      AS low_coverage
        FROM patient
    """).strip()

    cursor = conn.cursor()
    cursor.execute(query)
    row = cursor.fetchone()
    cursor.close()

    if not row or row[0] is None:
        print("  WARNING: No data returned for coverage_distribution. Skipping chart.")
        return

    high_n, med_n, low_n = int(row[0] or 0), int(row[1] or 0), int(row[2] or 0)

    tiers   = ["High\n(≥$10K)", "Medium\n($5K–$10K)", "Low\n(<$5K)"]
    counts  = [high_n, med_n, low_n]
    colors  = ["#3A9E63", "#4682B4", "#888888"]   # green, blue, gray

    _apply_chart_style()
    fig, ax = plt.subplots(figsize=(8, 6))

    bars = ax.bar(
        tiers, counts,
        color=colors,
        edgecolor="white",
        linewidth=0.8,
        width=0.5,
    )

    # Annotate bars with count on top
    for bar, v in zip(bars, counts):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + max(counts) * 0.015,
            _fmt_count(v),
            ha="center",
            va="bottom",
            fontsize=11,
            fontweight="bold",
            color="#333333",
        )

    ax.set_ylabel("Number of Patients", fontsize=11, labelpad=8)
    ax.set_title("Patient Healthcare Coverage Distribution", fontsize=14, fontweight="bold", pad=14)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.set_ylim(0, max(counts) * 1.15)
    ax.tick_params(axis="x", labelsize=11)
    ax.tick_params(axis="y", labelsize=9)

    fig.tight_layout()
    _save_fig(fig, output_path)
    plt.close(fig)


# ---------------------------------------------------------------------------
# DB connection
# ---------------------------------------------------------------------------

def connect_db(args: argparse.Namespace):
    """Connect to MySQL and return the connection object, or None on failure."""
    try:
        import mysql.connector  # type: ignore[import-not-found]
    except ImportError:
        print("  WARNING: mysql-connector-python not installed. Charts will be skipped.")
        return None

    password = args.password
    if password is None:
        try:
            password = getpass.getpass(f"MySQL password for {args.user}@{args.host}: ")
        except (KeyboardInterrupt, EOFError):
            print("\nPassword entry cancelled. Charts will be skipped.")
            return None

    try:
        conn = mysql.connector.connect(
            host=args.host,
            port=args.port,
            user=args.user,
            password=password,
            database=args.database,
            charset="utf8mb4",
            use_pure=True,
            connection_timeout=30,
        )
        return conn
    except mysql.connector.Error as exc:
        print(f"  WARNING: Could not connect to MySQL: {exc}")
        return None


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the 4 chart PNGs for the INFO 579 portfolio project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
            Examples:
              python scripts/generate_charts.py --user matthewqthompson --database Final_Project
              MYSQL_PASSWORD=secret python scripts/generate_charts.py --user root
        """),
    )
    parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="MySQL host (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port",
        default=3306,
        type=int,
        help="MySQL port (default: 3306)",
    )
    parser.add_argument(
        "--user",
        default=os.environ.get("MYSQL_USER", "root"),
        help="MySQL user (default: $MYSQL_USER or root)",
    )
    parser.add_argument(
        "--password",
        default=os.environ.get("MYSQL_PASSWORD"),
        help="MySQL password (default: $MYSQL_PASSWORD; omit to prompt)",
    )
    parser.add_argument(
        "--database",
        default="Final_Project",
        help="Target database name (default: Final_Project)",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help=(
            "Directory where PNG files will be written "
            "(default: images/ at the project root)"
        ),
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    # Resolve output directory
    if args.output_dir is not None:
        images_dir = Path(args.output_dir).resolve()
    else:
        images_dir = IMAGES_DIR

    images_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output directory: {images_dir}\n")

    # The ER diagram (schema_er_diagram.png) is a hand-curated screenshot,
    # not regenerated by this script. This script only produces the 4 chart PNGs.

    # --- DB connection ---
    print("Connecting to database...")
    conn = connect_db(args)

    if conn is None:
        print("\nSkipping all charts due to missing DB connection.")
        return

    print("  Connected. ✓\n")

    chart_tasks = [
        (
            "top_conditions",
            images_dir / "top_conditions.png",
            generate_top_conditions,
        ),
        (
            "top_procedures",
            images_dir / "top_procedures.png",
            generate_top_procedures,
        ),
        (
            "top_providers",
            images_dir / "top_providers.png",
            generate_top_providers,
        ),
        (
            "coverage_distribution",
            images_dir / "coverage_distribution.png",
            generate_coverage_distribution,
        ),
    ]

    for chart_name, out_path, fn in chart_tasks:
        print(f"Generating {chart_name} chart...")
        try:
            fn(conn, out_path)
            print("  Done. ✓")
        except Exception as exc:
            print(f"  ERROR generating {chart_name}: {exc}")

    conn.close()
    print("\nAll images generated.")


if __name__ == "__main__":
    main()
